### ISSUE TITLE
Support OBS on Windows 10

### ISSUE THREAD

**Issue by fredgalvao** [ezsoftware/OverlayPlugin-Compiler#2]
I've done some extensive research into making the Overlay plugin work with OBS window capture on Windows 10, since disabling aero isn't an option/thing. It seems the only thing available is this https://github.com/RainbowMage/OverlayPlugin/issues/44.

@dartvalince seems to have fixed it, but there is no PR for the changes, not on RainbowMage's repo nor here. His changes are quite clear on his explanation of the issue and seemingly easy to merge. Is there any change we can get those changes here and compile a new version? If we're worried about the popups he mentioned, we could have a diff build for it not to mess with the current release files.

However, I'd be gratefull if I found any other workaround to make it work without having to use a new version, like messing somewhere on OBS.

**Comment by ezsoftware** [comment]
Over the weekend I'll add his changes (looks like he removed 1 line and added 2, so easy changes to make) and test it out.  If I don't find any issues with it and it works properly, I'll submit a pull request to RainbowMage with it, if it does have issues (which it may, the issue seems to mention a lot of popup windows that need to be closed?) then I'll look at just leaving them in the Streamer branch (provided it does work with OBS window capture).

**Comment by manbeardgames** [comment]
Hey @ezsoftware made a post about it on reddit [here](https://www.reddit.com/r/ffxiv/comments/4ah21u/rainbowmage_obs_support_no_black_box_issue_need/).  Had a few people test it with the change i made, and it worked on Windows 10.  Only issue is the multiple pop ups that occur due to the changes. 

Honestly, I wasn't able to spend much time with the code as I wanted to really deduce why, and I'm not familiar with the Xilium.CefGlue library. It always creates 2 popup windows for each window type (mIni parse, spell timer, etc), one of which is a dud and the other is legit.  Closing both out then clicking the Reload Overlay will give the single window that works.  

I'm releasing my FFXIV Gathering App tomorrow, so I'll have some more down time to go over the Overlay code more, but if there is anything I can help with, I'd be happy too.
